name: Build caddy-linux-amd64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: install go
      uses: actions/setup-go@v3
      with: 
        go-version: '1.16'
        check-latest: true
    
    - name: install xcaddy
      run: |
        latest_version="$(wget -qO- -t1 -T2 "https://api.github.com/repos/caddyserver/xcaddy/releases" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g')"
        echo "${latest_version}"
        latest_name="$(wget -qO- -t1 -T2 "https://api.github.com/repos/caddyserver/xcaddy/releases" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/v//g;s/,//g;s/ //g')"
        echo "${latest_name}"
        wget https://github.com/caddyserver/xcaddy/releases/download/${latest_version}/xcaddy_${latest_name}_linux_amd64.tar.gz
        tar -zxvf xcaddy_*_linux_amd64.tar.gz

    - name: build caddy
      run: |
        ./xcaddy build \
          --with github.com/mholt/caddy-l4 \
          --with github.com/mholt/caddy-dynamicdns \
          --with github.com/caddy-dns/cloudflare

    - name: upload
      uses: actions/upload-artifact@master
      with:
        name: caddy-linux-amd64
        path: ./caddy
