name: Build caddy-linux-amd64

on:
  workflow_dispatch:
  push:
    paths:
      - 'caddy-linux-amd64.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: install go
      uses: actions/setup-go@master
    
    - name: install xcaddy
      run: |
        tag_name=`curl -s https://api.github.com/repos/caddyserver/xcaddy/releases | grep 'tag_name' | sed -n '1p' | cut -d\" -f4`
        wget https://github.com/caddyserver/xcaddy/releases/download/${tag_name}/xcaddy_${tag_name}_linux_amd64.tar.gz
        tar -zxvf xcaddy_*_linux_amd64.tar.gz

    - name: build caddy
      run: |
        ./xcaddy build \
          --with github.com/mholt/caddy-l4 \
          --with github.com/mholt/caddy-dynamicdns \
          --with github.com/caddy-dns/cloudflare

    - name: upload
      uses: actions/upload-artifact@master
      with:
        name: caddy-linux-amd64
        path: ./caddy2
