name: Deploy ChatGPT-Next-Web V3 to Vercel

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Vercel CLI
      run: npm i -g vercel --registry http://registry.npmmirror.com

    - name: Clone repository
      run: git clone https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web.git -b v3

    - name: Change directory
      run: cd ChatGPT-Next-Web

    - name: Deploy to Vercel
      run: |
        npm run buil
        dvercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes --name ChatGPT-Next-Web-V3
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
