name: Deploy Kimi to Vercel

on:
  push:
    branches:
      - main # or the branch you want to trigger the deployment on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        repository: 'LLM-Red-Team/kimi-free-api'
        path: 'kimi-free-api'

    - name: Deploy to Vercel
      run: |
        docker run -t --rm -v $PWD/kimi-free-api:/app -w /app -e VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }} sineverba/vercel-cli vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes --name kimi-free-api
