name: Build sing-box with wireguard

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
          - goarch: arm64
            goos: linux
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: install go
      uses: actions/setup-go@v3
      with: 
        go-version: '1.20'
        check-latest: true
    
    - name: install sing-box
      run: |
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go install -v -tags with_wireguard -tags with_reality_server github.com/sagernet/sing-box/cmd/sing-box@latest
    
    - name: Rename for Windows 
      if: matrix.goarch == 'amd64'
      run: |
        mkdir /home/runner/go/bin/linux_amd64
        mv /home/runner/go/bin/sing-box /home/runner/go/bin/linux_amd64/sing-box
        
    - name: upload
      uses: actions/upload-artifact@master
      with:
        name: sing-box-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
        path: /home/runner/go/bin
