name: Build sing-box-amd64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: install go
      uses: actions/setup-go@v3
      with: 
        go-version: '1.18.5'
        check-latest: true
    
    - name: install sing-box
      run: |
        go install -v -tags with_wireguard github.com/sagernet/sing-box/cmd/sing-box@latest

    - name: upload
      uses: actions/upload-artifact@master
      with:
        name: sing-box
        path: ./bin
